[project]
name = "python-template-repo"
version = "0.1.0"
description = "Template for Python projects with modular components"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "calculator @ {root}/src/components/calculator",
    "logger @ {root}/src/components/logger",
    "notifier @ {root}/src/components/notifier",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests", "src/components"]
python_files = ["test_*.py"]
addopts = "-v --cov"

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = []

[tool.ruff.isort]
known-first-party = ["calculator", "logger", "notifier"]

[project.urls]
repository = "https://github.com/yourusername/python-template-repo"
