version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest tests/ --junitxml=test-results/junit.xml --cov=src --cov-report=xml
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: coverage.xml

workflows:
  version: 2
  test-workflow:
    jobs:
      - test