version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            uv install
      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/junit.xml --cov=src --cov-report=xml --cov-report=html
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: htmlcov
      - store_test_results:
          path: test-results

workflows:
  version: 2
  run-tests:
    jobs:
      - run-tests
